config/routes.rb
Comparendo::Application.routes.draw do


  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags

    resources :events
    resources :leads
    resources :projects
    resources :messages

    root :to => 'events#index'
  end

  resources :contacts

  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
      get :company
      put :company 
      get :billing
      put :billing      
    end
  end

  # translated path
  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4' => "company#eintragen4", :as => 'company_add4'

  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  resources :quotes, :only => [:edit, :update], :as => :projects
  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details
  
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"  
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory_synonym"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/controllers/quotes_controller.rb
# encoding: utf-8
class QuotesController < ApplicationController
	before_filter :check_params, only: [:new]
	add_breadcrumb I18n.t(:home), nil
  add_breadcrumb I18n.t(:requestoffer), '/offerte-anfordern'

  def edit
    add_breadcrumb I18n.t(:add_project_info), request.fullpath
    @project = Project.find_by_id params[:id]
    redirect_to new_offer_path and return if @project.nil?

    @region = @project.region
    unless @project.options.empty?
      @subcategory = @project.options.first.question.subcategory
    end

    @category = @subcategory.category
    render :new
  end

  def new
    add_breadcrumb I18n.t(:add_project_info), request.fullpath
  	@project = Project.new
  end

  def create
    @subcategory = Subcategory.find params[:project].delete(:subcategory_id)
    @region = Region.find_by_id(params[:project][:region_id])

    specialties_attr = params[:project].delete(:specialties)
    attrs = params[:project].merge({subcategory: @subcategory})
    @project = Project.new attrs

    # answers for textarea
    unless params[:options].blank?
      params[:options].values.each do |opt|
        answ = Answer.create(opt[:answer])
        @project.project_options << ProjectOption.new(option: answ)
      end
    end

    @project.tags << prepare_specialties(specialties_attr)
    @project.region = @region
    if @project.save
      flash[:notice] = "Das Projekt wurde erfolgreich erstellt"
      render :show
    else
      flash[:error] = "Projekt nicht erstellt."
      render :new
    end

  end

  def update
    @subcategory = Subcategory.find params[:project].delete(:subcategory_id)
    @region = Region.find_by_id(params[:project][:region_id])

    specialties_attr = params[:project].delete(:specialties)
    attrs = params[:project].merge({subcategory: @subcategory})
    
    @project = Project.find_by_id params[:id]
    @project.tags << prepare_specialties(specialties_attr)
    if @project.update_attributes attrs
      flash[:notice] = "Das Projekt wurde erfolgreich erstellt"
      render :show
    else
      flash[:error] = "Projekt nicht erstellt."
      render :new
    end
  end

  def show
  	@project = Project.find params[:id]
  end

  private
    def check_params
      redirect_to new_offer_path and return if params[:subcategory_id].blank?

      @subcategory = Subcategory.find params[:subcategory_id]
      redirect_to new_offer_path and return if @subcategory.nil?

      @category = @subcategory.category
      @region = Region.find_by_id(params[:region_id]) unless params[:region_id].blank?
    end

    def prepare_specialties str_specialties
      current_specialties = @project.tags
      new_specialties = []
      for_destroy = []
      for_create = []

      unless str_specialties.blank?
        str_specialties.split(",").uniq.each do |name|
          new_specialties << Tag.find_or_create_by_name(name: name)
        end
        new_specialties.uniq! unless new_specialties.empty?
      end

      for_destroy = current_specialties - new_specialties
      for_create = new_specialties - current_specialties

      for_destroy.each do |s|
        scp = Tagging.of_tag(s)
        scp = scp.of_taggable(@project)
        scp.destroy_all
      end
      for_create
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def build_project_option_field p, q, answered=[]
    if q.checkbox?
      return build_checkboxes_field(q,answered, p)
    end

    if q.select?
      return build_select_field(q,answered, p)
    end

    if q.custom?
      return build_text_field(q,answered, p)
    end
  end

  def build_checkboxes_field q, answered=[], p
    res = []
    q.answers.each do |a|
      indx = project_option_indx
      checked = !answered.empty? && answered.include?(a)
      f = check_box_tag("project[project_options_attributes][#{indx}][answer_id]", a.id, checked)
      f += label_tag("project_project_options_attributes_#{indx}_answer_id", a.description, style: "display: inline;")

      po = ProjectOption.where(project_id: p.id, answer_id: a.id).first
      # if p not new record add additional field
      f += hidden_field_tag( "project[project_options_attributes][#{indx}][id]", po.id) if po

      res << content_tag(:fieldset, f)
    end
    res.join("").html_safe
  end

  def build_select_field q, answered=[], p
  	indx = project_option_indx
    res = "<select name='project[project_options_attributes][#{indx}][answer_id]'>"
    res += "<option>Bitte Auswahl treffen</option>" if q.is_mandatory?
    po = nil
    q.answers.each do |a|
      selected = !answered.empty? && answered.include?(a)
    	if selected
	      res += "<option value='#{a.id}' selected='selected'>#{a.description}</option>"
	      po = ProjectOption.where(project_id: p.id, answer_id: a.id).first
	    else
	      res += "<option value='#{a.id}'>#{a.description}</option>"
	    end
    end
	  res += "</select>"
		
    res += hidden_field_tag("project[project_options_attributes][#{indx}][id]", po.id) if po

	  res.html_safe
	end

  def build_text_field q, answered=[], p
		indx = project_option_indx
		content = nil
		unless answered.empty?
			content = answered.first.description
			po = ProjectOption.where(project_id: p.id, answer_id: answered.first.id).first
		end
    res = text_area_tag "options[#{indx}][answer][description]", content, cols: 40, rows: 5, class: 'custom_question'
    res += hidden_field_tag "options[#{indx}][answer][question_id]", q.id
    
    res += hidden_field_tag("project[project_options_attributes][#{indx}][id]", po.id) if po

    res.html_safe
  end

  def project_option_indx  
    "#{SecureRandom.hex(3)}#{Time.now.to_i}"
  end
end

app/views/quotes/new.html.erb
<div id="main-left-wrapper">
    <h2>Geben Sie nun bitte einige zusätzliche Informationen zu Ihrem Projekt an</h2>
    <% url = @project.new_record? ? create_quote_details_path :  project_path(@project) %>
    <%= form_for @project, url: url, html: {id: 'quote_details_form'} do |f| %>

        <% @subcategory.questions.each do |q| %>
            <label>
              <%= q.description %>
              <% if q.is_mandatory? %>
                <abbr title="mandatory">*</abbr>
              <% end %>
            </label>
            <% answered=[] %>
            <% answered = @project.project_options.map{|po| po.option if po.option && po.option.question_id==q.id }.compact %>
            <%= build_project_option_field(@project, q, answered) %>
            <% unless @project.errors.messages[:"quotes_#{q.id}"].blank? %>
              <label for="project_description" generated="true" class="error">
                <%= @project.errors.messages[:"quotes_#{q.id}"].join(',') %>
              </label>
            <% end %>
            <hr>
        <% end %>

        <div class="clearfix margintop50px">
            <%= f.label t('.description') %>
            <%= f.text_area :description, :rows => 5 %>
        </div>

        <!-- TODO numeric field + currency field, default 1000 CHF -->
        <div class="clearfix budget border-section">
            <%= f.label t('.budget') %>
            <%= f.text_field :budget, value: "1000", class: "clearme" %>
            <%= f.select(:currency, [['CHF', "CHF"], ['EUR', "EUR"], ['USD', "USD"]],{:class => "clearme", :multiple => false})%>
        </div>

        <!-- TODO timeframe (Start-End, two calendar selects) -->
        <div class="clearfix timeframe border-section">
            <label><%=t('.time_frame')%></label>
            <div>
                <%= f.label t('.start_date') %>
                <%= f.text_field :start_date, class: "calendar" %>
                <%= f.label t('.end_date') %>
                <%= f.text_field :end_date, class: "calendar" %>
            </div>
        </div>
      <div class="clearfix border-section">
          <div id="location-toggle-button">
            <% if @region %>
              <input type="checkbox" checked="checked"/>
              <input type="hidden" name="project[region_id]" id="project_region_id" value="<%= @region.id %>"/>
            <% else %>
              <input type="checkbox"/>
              <input type="hidden" name="project[region_id]" id="project_region_id" value=""/>
            <% end %>
          </div>
          <% if @region %>
            <%= select_tag :region, options_for_select(Region.all.map{|r| [r.name, r.id]}, @region.id ), :title => t('hints.website'),:data => {:placement=>'right'}, :class => "add_tooltip" %>
          <% else %>
            <%= select_tag :region, options_for_select(Region.all.map{|r| [r.name, r.id]}), style: "display: none;" , :title => t('hints.website'),:data => {:placement=>'right'}, :class => "add_tooltip"%>
          <% end %>
        </div>

        <div class="clearfix border-section tags">
          <%= f.label t('company_form.specialties') %>
          <% specialties = @project.tags.map(&:name).join(",") %>
          <%= text_field_tag "project[specialties]", specialties, {:class => 'tagsinputtable tooltippable',
          :data => {:autocomplete_source=>autocomplete_company_specialties_path}} %>
        </div>
        <hr>
        <%= f.hidden_field :subcategory_id, value: @subcategory.id %>
        <%#= f.hidden_field :region_id, value: @region.id if @region %>
        <%= f.hidden_field :id, value: @project.id unless @project.new_record? %>
        <div class="clearfix">
            <%= f.submit 'Weiter' %>
        </div>
    <% end %>
</div>

<div id="main-right-wrapper">
  <h3><%= t(:how_does_it_work) %></h3>
  <ul>
    <li class="one-bul"><a href="#">Kurzes Formular</a></li>
    <li class="two-bul"><a href="#">Abschicken</a></li>
    <li class="three-bul"><a href="#">3 Offerten erhalten</a></li>
  </ul>

  <div class="clr"><br><br><br></div>

  <%= render "layouts/latest_news"%>

  <div class="clr"><br><br><br></div>

  <h3>Top-Anbieter:</h3>
  <ul>
    <li><a href="#">Geprüft durch uns</a></li>
    <li><a href="#">Hintergrund-Check</a></li>
    <li><a href="#">Interview</a></li>
  </ul>
  
</div>  

<div class="clr"></div>
<script type="text/javascript">
  $(function() {
    $("input[type=checkbox]").click(function(){
      var arr = this.id.split("_");
      var indx = arr[4];
      if ($("#project_project_options_attributes_"+indx+"_id").length > 0) {
        if($(this).is(":checked")) {
          $("[name='project[project_options_attributes]["+indx+"][_destroy]']").remove();
        } else {
          $(this).parent().append(
            $('<input/>', {'name': "project[project_options_attributes]["+indx+"][_destroy]", 'type':'hidden', 'value': 1})
          )
        }
      }
    });
  });
</script>

app/views/quotes/show.html.erb
<h1>Geben Sie nun bitte einige zusätzliche Informationen zu Ihrem Projekt an</h1>
<div class="main-left-wrapper">
  <p>Description : <%= @project.description %></p>
  <p>Budget : <%= @project.budget %></p>
  <p>Timeframe : <%= @project.start_date.strftime("%m/%d/%Y") %> - <%= @project.end_date.strftime("%m/%d/%Y") %></p>
  <p>Location : <%= @project.region.nil? ? "all-of-Switzerland" : @project.region.name %></p>
  <p>Tags : <%= @project.tags.map(&:name).join(", ") %></p>
  <div>
    <% @project.options.map(&:question).uniq.each do |item| %>
      <%= item.name %>
      <ul>
      	<% @project.options.where(question_id: item.id).each do |option| %>
          <li><%= option.description %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="pull-left">
    <!-- TODO fix and move to de.yml -->
    <%= link_to "Zurück", edit_project_path(@project), class: "btn" %>
  </div>

  <div class="pull-right">
    <!-- TODO fix and move to de.yml -->
    <%= link_to "Weiter", "#notification-screen", class: "btn", :'data-toggle'=>"modal" %>
  </div>
</div>

<div id="notification-screen" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Offerte-Anfordern</h3>
	</div>
	<div class="modal-body">
		<p>The Offerte has been created.</p>
	</div>
	<div class="modal-footer">
		<a href="/" class="btn btn-primary">Ok</a>
	</div>
</div>