config/routes.rb
Comparendo::Application.routes.draw do


  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags

    resources :events
    resources :leads
    resources :projects
    resources :messages

    root :to => 'events#index'
  end

  resources :contacts

  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
      get :company
      put :company 
      get :billing
      put :billing      
    end
  end

  # translated path
  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4' => "company#eintragen4", :as => 'company_add4'

  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  resources :quotes, :only => [:edit, :update], :as => :projects
  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details
  
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"  
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory_synonym"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable,
         :trackable, :validatable, :omniauthable


  has_many :messages, :foreign_key => "to_id"
  has_many :sent_messages, :foreign_key => "from_id", :class_name => "Message"
  has_many :reviews
  has_one :company
  has_many :articles, :foreign_key => "author_id"
  has_many :projects

  image_accessor :image
  attr_accessible :first_name, :last_name, :name, :email, :description, :image, :password, :password_confirmation,
                  :remember_me, :provider, :uid, :confirmed_at, :author, :admin

  validates_presence_of :name
  validates_presence_of :email

  def name
    [self.first_name, self.last_name].join(' ').strip()
  end

  def name=(name)
    tokens = name.strip.split(/\s+/)
    self.first_name = self.last_name = nil

    self.first_name = tokens[0].titleize if tokens[0] and tokens[0]   =~ /[A-Za-z]+/
    self.last_name = tokens[1].titleize if tokens[1] and tokens[1] =~ /[A-Za-z]+/
  end

  def has_company?
    company
  end

  def is_author_of? article
    articles.include?(article)
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    #user = User.where(:provider => auth.provider, :uid => auth.uid).first
    names = auth.extra.raw_info.name.strip.split(/\s+/)
    user = User.where("provider = ? AND uid = ? OR (first_name = ? AND last_name = ?)", auth.provider, auth.uid, names.first, names.last).first
    unless user
      user = User.create(:first_name => names.first,
                         :last_name => names.last,
                         :provider => auth.provider,
                         :uid => auth.uid,
                         :email => auth.info.email,
                         :password => Devise.friendly_token[0,20],
                         :confirmed_at => DateTime.now
      )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :except => [:check_email]

  def check_email
    @user = User.find_by_email(params[:user][:email])
    respond_to do |format|
      format.json { render :json => !@user }
    end
  end

  def profil
    set_tab :profile
    @user = current_user
    @company = Company.find_by_user_id(@user["id"])
    
    if request.put?
      if @user.update_attributes(params[:user])
        flash[:notice] = 'Profil wurde erfolgreich aktualisiert.'
      else
        flash[:error] = @user.errors.values[0][0]
      end
    end
  end
  def company
    set_tab :profile
    @user = current_userrt.
      else
        flash[:error] = @user.errors.values[0][0]
      end
    end
  end
  def company
    set_tab :profile
    @user = current_user
    @company = Company.find_by_user_id(@user["id"])
    @region = Region.all
    @city = City.all
    
    
    if request.put?
       
      if @company.update_attributes(params[:company])
        flash[:notice] = 'Company information has be stored successfully'
      else
        flash[:error] = @company.errors.values[0][0]
      end
    end
  end 
  def billing
    set_tab :billing
    @user = current_user
    @user_billing = UsersBilling.find_by_user_id(@user["id"])
    
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/billing.html.erb
<h1> Billing </h1>

<%= form_for @user, :url => billing_users_path,
                 :html => {:id => 'user_edit_profile_form', :class => 'edit_user auto_validation_form'} do |f| %>

	<div class="clearfix">
		
		<%= label_tag :payment_method %>
		<%= select_tag("billing[payment_method_id]", 
			options_from_collection_for_select( PaymentMethod.all, "id", "method", (@user_billing.nil?) ? '' : @user_billing.payment_method_id )) %>
			
	</div>
	
	<div class="paypal_form">
		<%= f.label :paypal_address %>
		<%= text_field_tag :paypal_address %>
	</div>	
	<div class="creditcard_form">
		<div class="clearfix">
			<%= f.label :creditcard_type %>	
			<%= select_tag("billing[creditcard_id]", 
				options_from_collection_for_select( CreditcardType.all, "id", "name", '1' )) %>
		</div>
		<div class="clearfix">
			<%= f.label :exp_year %>
			<%= text_field_tag :exp_year %>			
		</div>
		<div class="clearfix">
			<%= f.label :exp_month %>
			<%= text_field_tag :exp_month %>			
		</div>
		<div class="clearfix">
			<%= f.label :cvv2 %>
			<%= text_field_tag :cvv2 %>			
		</div>
	</div>
	<div class="banktransfer_form">
		<div class="clearfix">
			<%= f.label :bank_transfer %>
			<%= text_field_tag :bank_transfer %>			
		</div>
	</div>		
	<div class="clearfix">
		<%= f.submit 'save' %>
    </div>
<% end %>

app/views/users/company.html.erb
<h1> My Company </h1>

    <%= form_for @company, :url => company_users_path,
                 :html => {:id => 'user_edit_profile_form', :class => 'edit_user auto_validation_form'} do |f| %>
        <div class="clearfix">
            <%= f.label :name %>
            <%= f.text_field :name, :class => "tooltippable add_tooltip", :title => t('hints.official_company_name'),            
            :class => "tooltippable add_tooltip" ,
            "data-placement" => "right",  "data-trigger" => "focus"  
             %>
        </div>
		<div class="clearfix">
            <%= f.label :address %>
            <%= f.text_field :address, :class => "tooltippable add_tooltip", :title => t('hints.address'), 
            :class => "tooltippable add_tooltip" ,
            "data-placement" => "right",  "data-trigger" => "focus"
             %>
        </div>

		<div class="clearfix">
            <%= f.label :email %>
            <%= f.text_field :email, :class => "tooltippable add_tooltip", :title => t('hints.email'),
            :class => "tooltippable add_tooltip" ,
            "data-placement" => "right",  "data-trigger" => "focus"            
             %>
        </div>
        
        <div class="clearfix">
        	<%= f.label :region %>
        	<%= select_tag("company[region_id]", options_from_collection_for_select(Region.all, "id", "name", @company.region_id ) )%>
        </div>          
        <div class="clearfix">
        	<%= f.label :city %>
        	<%= select_tag("company[city_id]", options_from_collection_for_select(City.all, "id", "name", @company.city_id ) )%>
        </div>        
        
        <div class="clearfix">
            <%= f.label :phone_numbers %>
            <%= text_field_tag "company[phone_numbers][]", @company["phone_numbers"], 
            :title => t('hints.website'), 
            :class => "tooltippable add_tooltip" ,
            "data-placement" => "right",  "data-trigger" => "focus"
            
            %>
        </div>
        <div class="clearfix">
            <label class="form-label"><%= t(:website) %></label>
  				<% unless @company.websites.nil? %>
					<% @company.websites.each do |website| %>
			  			<div class="control-group">
							<input class="company_website tooltippable add_tooltip" name="company[websites][]" type="text"
			       				title="<%= t('hints.website') %>"
			       			value="<%= website %>" data-placement="right" data-trigger='focus'/>
			  			</div>
					<% end %>
			  <% end %>
        </div>
        <div class="clearfix">
            <%= f.label :postal_code %>
            <%= f.text_field :postal_code, :class => "tooltippable", :title => t('hints.postal_code'),
            :class => "tooltippable add_tooltip" ,
            "data-placement" => "right",  "data-trigger" => "focus"
             %>
        </div>
        <div class="clearfix">
            <%= f.label :description %>
            <%= f.text_area :description, :rows => 5, :title => t('hints.phone'), :class => "tooltippable",
            :class => "tooltippable add_tooltip" ,
            "data-placement" => "right",  "data-trigger" => "focus"
            %>
        </div>
        
        <div class="clearfix">
            <%= f.submit 'save' %>
        </div>
    <% end %>

app/views/users/profil.html.erb
<div class="main-left-wrapper">
    <%= form_for @user, :url => profil_users_path,
                 :html => {:id => 'user_edit_profile_form', :class => 'edit_user auto_validation_form'} do |f| %>
        <div class="clearfix">
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>
		<div class="clearfix">
            <%= f.label :email %>
            <%= f.text_field :email %>
        </div>
		<div class="clearfix">            
            <%= check_box_tag :notification %> Enable notification            
        </div>
        <div class="clearfix">
        	<br/>
        </div>
        <div class="clearfix">
            <%= f.label :password %>
            <%= f.password_field :password %>
        </div>        
        <div class="clearfix">
            <%= f.label :image %>
            <% if @user.image_uid %>
                <%= image_tag @user.image.thumb('200x140').url if @user.image_uid %>
            <% else %>
                <%= image_tag 'company-icon.jpg' %>
            <% end %>
        </div>
        <div class="clearfix">
            <%= f.file_field :image %>
        </div>

        <div class="clearfix">
            <%= f.label :description %>
            <%= f.text_area :description, :rows => 5 %>
        </div>
		<div class="clearfix">
			<br />			
		</div>
		
        <div class="clearfix">
            <%= label_tag :company %>
            
            <% if @company.nil? %>
            	<%= link_to company_add_url, :class => '' do %>
	            	<span id="span"> Register Company </span>
	            <% end %>            
            <% else %>            
	            <%= link_to company_users_path, :class => '' do %>
	            	<span id="span"> <%= @company["name"] %> </span>
	            <% end %>            
            <% end %>
        </div>        
		<div class="clearfix">
			<br />			
		</div>
        <div class="clearfix">
            <%= f.submit 'save' %>
        </div>
    <% end %>
</div>