config/routes.rb
Comparendo::Application.routes.draw do


  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags

    resources :events
    resources :leads
    resources :projects
    resources :messages

    root :to => 'events#index'
  end

  resources :contacts

  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
      get :company
      put :company 
      get :billing
      put :billing      
    end
  end

  # translated path
  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4' => "company#eintragen4", :as => 'company_add4'

  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  resources :quotes, :only => [:edit, :update], :as => :projects
  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details
  
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"  
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory_synonym"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  set_tab :home
  before_filter :newest_infos, :only => :index

  def index
    append_meta_tag_description "Regionales Firmenverzeichnis und Offertenportal"
    append_meta_tag_keywords "Webverzeichnis, Firmenverzeichnis, Gelbe Seiten, Offertenportal, Offerten, Architekten, Architekten Schweiz"
    append_page_title "Die besten Anbieter der Schweiz"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('.tab-container').easytabs();
    });
  </script>
<% end %>
<!-------------------------------------->
<% unless response.status==404 %>
    <%= content_for :banner do %>
      <div id="banner-wrapper">
        <div id="banner-wrapper-inner">

            <div id="banner-left-wrapper">
                <img src="/assets/old-lady.png" width="251" height="353" />
                  <p style="margin-top:-45px;">“Comparendo hat für uns sehr schnell mehrere attraktive Offerten gefunden, vielen Dank nochmals.” <br />
      <em>~Regina Stauffenbach, SZ</em></p>
              </div>
              <div id="banner-right-wrapper">
                <h1>Finden Sie mit uns die besten<br />Anbieter für Ihr Projekt. </h1>
                  <div id="banner-list-wrapper">
                    <ul>
                        <li>Auf Knopfdruck 3-5 qualitativ hochwertige Offerten</li>
                        <li>Wir suchen für Sie unter den besten Profis Ihrer Region</li>
                        <li>Kompetente und kostenfreie Beratung inklusive</li>
                      </ul>
                  </div>
                  <div class="clr"></div>
                <%= button_to "Jetzt Starten", new_offer_path, :id => "start-btn", :class => "jetztbutton", :method => :get %>
              </div>
          </div>
      </div>
    <% end %>
<% end %>
<!-------------------------------------      -->
<div id="main-left-wrapper">
  <% unless response.status==404 %>
  <!--///////////////////////////-->
  <h2><%= t('home_page.title') %></h2>
  <p style='padding-right: 20px;'><%= t('home_page.intro') %></p>

  <br />

  <div id="searchtable">
    <%= form_tag company_index_url, :method => :get do %>
      <%= t(:im_looking_for) %>
        <%= text_field_tag "q", "Solaranlagen",
                           {:id=>"industry", :class=>"gray autocomplete clearme",
                            :data => {:autocomplete_source=>autocomplete_category_subcategory_synonym_path}} %>


        in
        <%= text_field_tag "region", "Zürich",
                           {:id=>"area", :class=>"gray clearme autocomplete",
                            :data => {:autocomplete_source=>autocomplete_region_city_path}} %>


        <input id="search" value="<%= t('general.find') %>" type="submit" class="button">
    <% end %>
  </div>

  <br />

  <br />

  <div id="map-switzerland" style="z-index:1;">
    <ul class="switzerland">
      <% Country.where(:name => 'Switzerland').first.regions.order(:name).each_with_index do |r,i| %>
        <li class="ch<%= i+1 %>">
          <a href="javascript:mapClick('<%= r.name %>')"><%= r.name %></a>
        </li>
      <% end %>

    </ul>
  </div>

  
  
<% else %>
  <div id="banner-wrapper">
    <div id="err-wrapper">
    
      <div id="main-left-wrapper">
          <h2>Seite nicht gefunden</h2>
          
          <p>
          Die von Ihnen angeforderte Seite existiert nicht. Vielleicht haben Sie sich vertippt, oder die Website-Struktur hat sich
          geändert. Falls Sie denken, dass diese Seite existieren sollte, oder Sie automatisch hierhin gelangt sind, benachrichtigen
          Sie uns bitte über das <a href='/kontakt'>Kontaktformular</a>.
          
          </p>
      </div>
      
    </div>
  </div>
<% end %>
  <!--////////////////////////////-->
</div>


<div id="main-right-wrapper">


  <%= render "layouts/how_does_it_work"%>
  
  <div class="clr"><br><br><br></div>

  <%= render "layouts/latest_news"%>

  <div class="clr"><br><br><br></div>  

  <%= render "layouts/top_providers"%>


</div>
<div class="clr"></div>
<script>

  $('#map-switzerland').cssMap({
    'size' : 660,
    'cities' : true,
    'searchUrl' : 'search',
    'loadingText' : 'Lade...',
    'onClick': function(e) {

    }

  });

</script>