config/routes.rb
Comparendo::Application.routes.draw do


  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags

    resources :events
    resources :leads
    resources :projects
    resources :messages

    root :to => 'events#index'
  end

  resources :contacts

  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
      get :company
      put :company 
      get :billing
      put :billing      
    end
  end

  # translated path
  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4' => "company#eintragen4", :as => 'company_add4'

  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  resources :quotes, :only => [:edit, :update], :as => :projects
  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details
  
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"  
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory_synonym"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/project.rb
class Project < ActiveRecord::Base
  AVAILABLE_STATUS = [ :open, :assigned_to_a_company, :closed, :cancelled ]
  belongs_to :user
  belongs_to :region

  has_many :project_options
  has_many :options, through: :project_options

  has_many :tags, :through => :taggings
  has_many :taggings, :as => :taggable

  has_many :attachments, :as => :parent

  scope :opened, where(status: "open")

  has_many :messages

  has_many :company_projects
  has_many :companies, :through => :company_projects

  before_create :set_default_status
  accepts_nested_attributes_for :project_options, allow_destroy: true

  attr_accessible :name, :budget, :start_date, :end_date, :data,
                  :user, :description, :long_description,
                  :date, :timeframe, :attachments,
                  :project_options_attributes, :region_id, :currency, :subcategory

  attr_accessor :subcategory

  validates_uniqueness_of :name, :scope => :project_type_id

  validate :starts_at_is_less_than_ends_at,
           :starts_at_is_less_than_today,
           :quote_options, :check_status
  serialize :data, JSON

  def title
    self.name.blank? ? "No title" : self.name
  end

  def posted_ago
    require 'code_extensions.rb'
    CodeExtensions::TIME_AGO.(created_at)
  end

  def category
    options.empty? ? nil : options.first.question.subcategory.category
  end

  private

  def check_status
    errors.add(:status, " should be in #{AVAILABLE_STATUS.join(', ')}") unless self.status.blank? || AVAILABLE_STATUS.include?(self.status)
  end

  def quote_options
    if subcategory
      subcategory.questions.where(is_mandatory: true).each do |q|
        if Answer.where(id: project_options.map(&:answer_id)).where(question_id: q.id).empty?
          # TODO fix and move message to de.yml
          errors.add(:"quotes_#{q.id}", 'Bitte beantworten Sie diese Frage')
        end
      end
    end
  end

  def starts_at_is_less_than_ends_at
    if self.end_date
      errors.add(:end_date, "Enddatum ist kleiner als das Startdatum") if (start_date > end_date)
    end
  end

  def starts_at_is_less_than_today
    if self.start_date
      errors.add(:start_date, "Startdatum ist weniger als heute") if (Date.today > start_date)
    end
  end

  def set_default_status
    self.status = :open if self.status.blank?
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  skip_load_and_authorize_resource
  set_tab :projects
  def index
    @projects = current_user.projects.order("created_at desc").page(params[:page]).per(10)
  end
end

app/views/admin/projects/index.html.erb
<div id="main-left-wrapper">
	<h1><%= t(:projects) %></h1>
	<div id="leads-search-wrapper">
		<%= form_tag(admin_leads_path, remote: true) do %>
			<%= label_tag 'name', "Search", for: "q" %>
    	<%= text_field_tag 'q', nil, placeholder: 'Enter your search query here' %>
    	<%= submit_tag "Go", disable_with: "Please wait..."%>
		<% end %>
	</div>
	<% @projects.each do |project| %>
		<div class="project">
			<div class='left_block'>
				<h4><%= project.title %></h4>
				<div class="icon thumbnail-container">
					<%= image_tag project.user.image.url if project.user.image %>
				</div>
				<span>
					Budget:
					<%= number_to_currency(project.budget, unit: project.currency) %>
				</span>
				<span>
					Region:
					<%= project.region.name if project.region %>
				</span>
				<% desc = "Posted #{project.posted_ago}" %>
				<% desc += " in Category #{project.category.name}" if project.category %>
				<p class="description"><%= desc %></p>
			</div>
			<div class='right_block'>
				<span class="status <%= project.status %>"><%= project.status ? t('project.status.' + project.status) : 'N/A' %></span>
			</div>
			<div class="conversation">
				<% project.messages.each_with_index do |message, i| %>
					<div class="company-container">
						<% c = message.sender.company %>
						<div class="thumbnail-container">
							<%= image_tag c.cover_image.url if c.cover_image %>
						</div>
						<div class="company-details-container">
							<div class="company-name-container">
              	<p class="company-name"><%= c.name %></p>
              </div>
              <div class="company-rating-container">
				        <div class="star readonly" score="<%= c.rating %>"></div>
				      </div>
						</div>
						<div class="message-body"><blockquote><%= message.body %></blockquote></div>
						<div class="tab-container" id="tab-container-<%= c.id %>">
				    <ul class="etabs">
				      <li class="tab active">
				        <a href="#tabs1-intro" class="active">Intro</a>
				      </li>
				      <li class="tab"><a href="#tabs-kontakt-<%= c.id %>">Kontakt</a></li>
				      <li class="tab"><a href="#tabs-katalog-<%= c.id %>">Katalog</a></li>
				      <li class="tab"><a href="#tabs-abbildungen-<%= c.id %>">Abbildungen</a></li>
				      <li class="tab"><a href="#tabs-referenzen-<%= c.id %>">Referenzen</a></li>
				      <li class="tab"><a href="#tabs-news-<%= c.id %>">News</a></li>
				    </ul>
						<div class="panel-container">
				      <div id="tabs-intro-<%= c.id %>" style="display: block;" class="active">
				       <p><%= raw c.description %></p>
				      </div>
				       <div id="tabs-kontakt-<%= c.id %>" style="display: none;">
				       <p>
				        <%= c.contact_person %>,
				        <%= c.email %>,
				        <%= c.websites.join(",") %>,
				        <%= c.phone_numbers.join(",") %>,
				        <%= c.address %>,
				        <%= c.postal_code %>
				       </p>
				      </div>
				      <div id="tabs-katalog-<%= c.id %>" style="display: none;">
				      <p>die passenden Anbieter fir Ihr Projekt.</p>
				      </div>
				      <div id="tabs-abbildungen-<%= c.id %>" style="display: none;">
				      <p>Anbieter fir Ihr Projekt.</p>
				      </div>
				      <div id="tabs-referenzen-<%= c.id %>" style="display: none;">
				      <p>Finden Sie mit wenigen Mausklicks die passenden</p>
				      </div>
				      <div id="tabs-news-<%= c.id %>" style="display: none;">
				      <p>Finden Sie mit wenigen</p>
				      </div>
				    </div>
				    </div>
						<div class="clr"></div>
						<div class="company-tags-container">
				    <% c.tags.each do |t| %>
				      <div class="company-tags">
				      <%= link_to company_index_url(:region => c.region, :tag => t.name) do %>
				        <%= t.name %>
				      <% end %>
				      </div>
				    <% end %>
				    </div>
						<div class="clr"></div>
						<div class="action">
							<input type="button" class="btn btn-success" value="Accept"/>
							<input type="button" class="btn btn-danger" value="Reply"/>
						</div>
						<div class="clr"></div>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
	<%= paginate @projects %>
</div>

<!-- <div id="main-right-wrapper">
</div> -->

<div class="clr"></div>